# version: "3.9"

networks:
  ms-network:
    driver: bridge

services:
  ms-administrador:
    build:
      context: ./ms-administrador
      dockerfile: Dockerfile
    container_name: ms-administrador
    ports:
      - "8104:80"
    networks:
      - ms-network

  ms-notificador:
    build:
      context: ./ms-notificador
      dockerfile: Dockerfile
    container_name: ms-notificador
    ports:
      - "8107:80"
    networks:
      - ms-network

  ms-mensajeria:
    build:
      context: ./ms-mensajeria
      dockerfile: Dockerfile
    container_name: ms-mensajeria
    ports:
      - "8105:80"
      - "8878:8878" # apertura de puerto para socket
    networks:
      - ms-network

  client-oauth:
    build:
      context: ./services/client-oauth
      dockerfile: Dockerfile
    container_name: client-oauth
    ports:
      - "8101:80"
    networks:
      - ms-network
    environment:
      - URL_HOST_LOCAL=localhost

  client-email:
    build:
      context: ./services/client-email
      dockerfile: Dockerfile
    container_name: client-email
    ports:
      - "8100:80"
    networks:
      - ms-network
    environment:
      - URL_HOST_LOCAL=localhost

  client-reporte:
    build:
      context: ./services/client-reporte
      dockerfile: Dockerfile
    container_name: client-reporte
    ports:
      - "8108:80"
    networks:
      - ms-network
    environment:
      - URL_HOST_LOCAL=localhost

  client-trx:
    build:
      context: ./services/client-trx
      dockerfile: Dockerfile
    container_name: client-trx
    ports:
      - "8103:80"
    networks:
      - ms-network
    environment:
      - URL_HOST_LOCAL=localhost

  client-service:
    build:
      context: ./services/client-service
      dockerfile: Dockerfile
    container_name: client-service
    ports:
      - "8102:80" # no encuentro el puerto a asignar por defecto se asigno el 8102
    networks:
      - ms-network
    environment:
      - URL_HOST_LOCAL=localhost